# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from reset.proto import types_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commands.proto',
  package='reset.proto.commands',
  serialized_pb=_b('\n\x0e\x63ommands.proto\x12\x14reset.proto.commands\x1a\x0btypes.proto\"\xb3\x02\n\x0e\x43lientToServer\x12-\n\x04join\x18\n \x01(\x0b\x32\x1d.reset.proto.commands.CmdJoinH\x00\x12/\n\x05leave\x18\x0b \x01(\x0b\x32\x1e.reset.proto.commands.CmdLeaveH\x00\x12\x38\n\ngame_start\x18\x14 \x01(\x0b\x32\".reset.proto.commands.CmdGameStartH\x00\x12<\n\x0c\x61\x63tion_queue\x18\x1e \x01(\x0b\x32$.reset.proto.commands.CmdActionQueueH\x00\x12>\n\raction_cancel\x18\x1f \x01(\x0b\x32%.reset.proto.commands.CmdActionCancelH\x00\x42\t\n\x07payload\"\x17\n\x07\x43mdJoin\x12\x0c\n\x04name\x18\x01 \x02(\t\"\n\n\x08\x43mdLeave\"\x0e\n\x0c\x43mdGameStart\"\xb2\x01\n\x0e\x43mdActionQueue\x12\x16\n\x0e\x61\x63tion_type_id\x18\x01 \x02(\r\x12\x0f\n\x07unit_id\x18\x02 \x02(\r\x12\x31\n\x04mode\x18\x03 \x01(\x0e\x32\x1d.reset.proto.types.ActionMode:\x04ONCE\x12\x16\n\x0etarget_unit_id\x18\x04 \x01(\r\x12,\n\x0btarget_cell\x18\x05 \x01(\x0b\x32\x17.reset.proto.types.vec2\"$\n\x0f\x43mdActionCancel\x12\x11\n\taction_id\x18\x01 \x02(\r')
  ,
  dependencies=[types_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLIENTTOSERVER = _descriptor.Descriptor(
  name='ClientToServer',
  full_name='reset.proto.commands.ClientToServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='join', full_name='reset.proto.commands.ClientToServer.join', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leave', full_name='reset.proto.commands.ClientToServer.leave', index=1,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_start', full_name='reset.proto.commands.ClientToServer.game_start', index=2,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action_queue', full_name='reset.proto.commands.ClientToServer.action_queue', index=3,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action_cancel', full_name='reset.proto.commands.ClientToServer.action_cancel', index=4,
      number=31, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='reset.proto.commands.ClientToServer.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=54,
  serialized_end=361,
)


_CMDJOIN = _descriptor.Descriptor(
  name='CmdJoin',
  full_name='reset.proto.commands.CmdJoin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='reset.proto.commands.CmdJoin.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=386,
)


_CMDLEAVE = _descriptor.Descriptor(
  name='CmdLeave',
  full_name='reset.proto.commands.CmdLeave',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=398,
)


_CMDGAMESTART = _descriptor.Descriptor(
  name='CmdGameStart',
  full_name='reset.proto.commands.CmdGameStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=414,
)


_CMDACTIONQUEUE = _descriptor.Descriptor(
  name='CmdActionQueue',
  full_name='reset.proto.commands.CmdActionQueue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_type_id', full_name='reset.proto.commands.CmdActionQueue.action_type_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit_id', full_name='reset.proto.commands.CmdActionQueue.unit_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='reset.proto.commands.CmdActionQueue.mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_unit_id', full_name='reset.proto.commands.CmdActionQueue.target_unit_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_cell', full_name='reset.proto.commands.CmdActionQueue.target_cell', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=595,
)


_CMDACTIONCANCEL = _descriptor.Descriptor(
  name='CmdActionCancel',
  full_name='reset.proto.commands.CmdActionCancel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_id', full_name='reset.proto.commands.CmdActionCancel.action_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=633,
)

_CLIENTTOSERVER.fields_by_name['join'].message_type = _CMDJOIN
_CLIENTTOSERVER.fields_by_name['leave'].message_type = _CMDLEAVE
_CLIENTTOSERVER.fields_by_name['game_start'].message_type = _CMDGAMESTART
_CLIENTTOSERVER.fields_by_name['action_queue'].message_type = _CMDACTIONQUEUE
_CLIENTTOSERVER.fields_by_name['action_cancel'].message_type = _CMDACTIONCANCEL
_CLIENTTOSERVER.oneofs_by_name['payload'].fields.append(
  _CLIENTTOSERVER.fields_by_name['join'])
_CLIENTTOSERVER.fields_by_name['join'].containing_oneof = _CLIENTTOSERVER.oneofs_by_name['payload']
_CLIENTTOSERVER.oneofs_by_name['payload'].fields.append(
  _CLIENTTOSERVER.fields_by_name['leave'])
_CLIENTTOSERVER.fields_by_name['leave'].containing_oneof = _CLIENTTOSERVER.oneofs_by_name['payload']
_CLIENTTOSERVER.oneofs_by_name['payload'].fields.append(
  _CLIENTTOSERVER.fields_by_name['game_start'])
_CLIENTTOSERVER.fields_by_name['game_start'].containing_oneof = _CLIENTTOSERVER.oneofs_by_name['payload']
_CLIENTTOSERVER.oneofs_by_name['payload'].fields.append(
  _CLIENTTOSERVER.fields_by_name['action_queue'])
_CLIENTTOSERVER.fields_by_name['action_queue'].containing_oneof = _CLIENTTOSERVER.oneofs_by_name['payload']
_CLIENTTOSERVER.oneofs_by_name['payload'].fields.append(
  _CLIENTTOSERVER.fields_by_name['action_cancel'])
_CLIENTTOSERVER.fields_by_name['action_cancel'].containing_oneof = _CLIENTTOSERVER.oneofs_by_name['payload']
_CMDACTIONQUEUE.fields_by_name['mode'].enum_type = types_pb2._ACTIONMODE
_CMDACTIONQUEUE.fields_by_name['target_cell'].message_type = types_pb2._VEC2
DESCRIPTOR.message_types_by_name['ClientToServer'] = _CLIENTTOSERVER
DESCRIPTOR.message_types_by_name['CmdJoin'] = _CMDJOIN
DESCRIPTOR.message_types_by_name['CmdLeave'] = _CMDLEAVE
DESCRIPTOR.message_types_by_name['CmdGameStart'] = _CMDGAMESTART
DESCRIPTOR.message_types_by_name['CmdActionQueue'] = _CMDACTIONQUEUE
DESCRIPTOR.message_types_by_name['CmdActionCancel'] = _CMDACTIONCANCEL

ClientToServer = _reflection.GeneratedProtocolMessageType('ClientToServer', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTTOSERVER,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.commands.ClientToServer)
  ))
_sym_db.RegisterMessage(ClientToServer)

CmdJoin = _reflection.GeneratedProtocolMessageType('CmdJoin', (_message.Message,), dict(
  DESCRIPTOR = _CMDJOIN,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.commands.CmdJoin)
  ))
_sym_db.RegisterMessage(CmdJoin)

CmdLeave = _reflection.GeneratedProtocolMessageType('CmdLeave', (_message.Message,), dict(
  DESCRIPTOR = _CMDLEAVE,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.commands.CmdLeave)
  ))
_sym_db.RegisterMessage(CmdLeave)

CmdGameStart = _reflection.GeneratedProtocolMessageType('CmdGameStart', (_message.Message,), dict(
  DESCRIPTOR = _CMDGAMESTART,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.commands.CmdGameStart)
  ))
_sym_db.RegisterMessage(CmdGameStart)

CmdActionQueue = _reflection.GeneratedProtocolMessageType('CmdActionQueue', (_message.Message,), dict(
  DESCRIPTOR = _CMDACTIONQUEUE,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.commands.CmdActionQueue)
  ))
_sym_db.RegisterMessage(CmdActionQueue)

CmdActionCancel = _reflection.GeneratedProtocolMessageType('CmdActionCancel', (_message.Message,), dict(
  DESCRIPTOR = _CMDACTIONCANCEL,
  __module__ = 'commands_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.commands.CmdActionCancel)
  ))
_sym_db.RegisterMessage(CmdActionCancel)


# @@protoc_insertion_point(module_scope)
