# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='types.proto',
  package='reset.proto.types',
  serialized_pb=_b('\n\x0btypes.proto\x12\x11reset.proto.types\"\x1c\n\x04vec2\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\">\n\x0bTerrainType\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\"1\n\x0cResourceType\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"[\n\x08UnitType\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1e\n\x16\x64\x65\x66\x61ult_action_type_id\x18\x03 \x01(\r\x12\x0c\n\x04tags\x18\x04 \x03(\t\"\xdb\x02\n\nActionType\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cunit_type_id\x18\x03 \x02(\r\x12\x38\n\x04\x63ost\x18\x04 \x03(\x0b\x32*.reset.proto.types.ActionType.ResourceCost\x12\x10\n\x08\x64uration\x18\x05 \x02(\x01\x12\x39\n\x0c\x64\x65\x66\x61ult_mode\x18\x06 \x02(\x0e\x32\x1d.reset.proto.types.ActionMode:\x04ONCE\x12>\n\x0btarget_type\x18\x07 \x02(\x0e\x32#.reset.proto.types.ActionTargetType:\x04NONE\x12\x13\n\x0btarget_tags\x18\x08 \x03(\t\x1a\x38\n\x0cResourceCost\x12\x18\n\x10resource_type_id\x18\x01 \x02(\r\x12\x0e\n\x06\x61mount\x18\x02 \x02(\r*0\n\x10\x41\x63tionTargetType\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x43\x45LL\x10\x01\x12\x08\n\x04UNIT\x10\x02*\"\n\nActionMode\x12\x08\n\x04ONCE\x10\x00\x12\n\n\x06REPEAT\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ACTIONTARGETTYPE = _descriptor.EnumDescriptor(
  name='ActionTargetType',
  full_name='reset.proto.types.ActionTargetType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CELL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNIT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=622,
  serialized_end=670,
)
_sym_db.RegisterEnumDescriptor(_ACTIONTARGETTYPE)

ActionTargetType = enum_type_wrapper.EnumTypeWrapper(_ACTIONTARGETTYPE)
_ACTIONMODE = _descriptor.EnumDescriptor(
  name='ActionMode',
  full_name='reset.proto.types.ActionMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ONCE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPEAT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=672,
  serialized_end=706,
)
_sym_db.RegisterEnumDescriptor(_ACTIONMODE)

ActionMode = enum_type_wrapper.EnumTypeWrapper(_ACTIONMODE)
NONE = 0
CELL = 1
UNIT = 2
ONCE = 0
REPEAT = 1



_VEC2 = _descriptor.Descriptor(
  name='vec2',
  full_name='reset.proto.types.vec2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='reset.proto.types.vec2.x', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='reset.proto.types.vec2.y', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=62,
)


_TERRAINTYPE = _descriptor.Descriptor(
  name='TerrainType',
  full_name='reset.proto.types.TerrainType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='reset.proto.types.TerrainType.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='reset.proto.types.TerrainType.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='reset.proto.types.TerrainType.tags', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=126,
)


_RESOURCETYPE = _descriptor.Descriptor(
  name='ResourceType',
  full_name='reset.proto.types.ResourceType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='reset.proto.types.ResourceType.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='reset.proto.types.ResourceType.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=177,
)


_UNITTYPE = _descriptor.Descriptor(
  name='UnitType',
  full_name='reset.proto.types.UnitType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='reset.proto.types.UnitType.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='reset.proto.types.UnitType.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_action_type_id', full_name='reset.proto.types.UnitType.default_action_type_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='reset.proto.types.UnitType.tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=270,
)


_ACTIONTYPE_RESOURCECOST = _descriptor.Descriptor(
  name='ResourceCost',
  full_name='reset.proto.types.ActionType.ResourceCost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_type_id', full_name='reset.proto.types.ActionType.ResourceCost.resource_type_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='reset.proto.types.ActionType.ResourceCost.amount', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=564,
  serialized_end=620,
)

_ACTIONTYPE = _descriptor.Descriptor(
  name='ActionType',
  full_name='reset.proto.types.ActionType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='reset.proto.types.ActionType.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='reset.proto.types.ActionType.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit_type_id', full_name='reset.proto.types.ActionType.unit_type_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='reset.proto.types.ActionType.cost', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='reset.proto.types.ActionType.duration', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='default_mode', full_name='reset.proto.types.ActionType.default_mode', index=5,
      number=6, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_type', full_name='reset.proto.types.ActionType.target_type', index=6,
      number=7, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_tags', full_name='reset.proto.types.ActionType.target_tags', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACTIONTYPE_RESOURCECOST, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=620,
)

_ACTIONTYPE_RESOURCECOST.containing_type = _ACTIONTYPE
_ACTIONTYPE.fields_by_name['cost'].message_type = _ACTIONTYPE_RESOURCECOST
_ACTIONTYPE.fields_by_name['default_mode'].enum_type = _ACTIONMODE
_ACTIONTYPE.fields_by_name['target_type'].enum_type = _ACTIONTARGETTYPE
DESCRIPTOR.message_types_by_name['vec2'] = _VEC2
DESCRIPTOR.message_types_by_name['TerrainType'] = _TERRAINTYPE
DESCRIPTOR.message_types_by_name['ResourceType'] = _RESOURCETYPE
DESCRIPTOR.message_types_by_name['UnitType'] = _UNITTYPE
DESCRIPTOR.message_types_by_name['ActionType'] = _ACTIONTYPE
DESCRIPTOR.enum_types_by_name['ActionTargetType'] = _ACTIONTARGETTYPE
DESCRIPTOR.enum_types_by_name['ActionMode'] = _ACTIONMODE

vec2 = _reflection.GeneratedProtocolMessageType('vec2', (_message.Message,), dict(
  DESCRIPTOR = _VEC2,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.types.vec2)
  ))
_sym_db.RegisterMessage(vec2)

TerrainType = _reflection.GeneratedProtocolMessageType('TerrainType', (_message.Message,), dict(
  DESCRIPTOR = _TERRAINTYPE,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.types.TerrainType)
  ))
_sym_db.RegisterMessage(TerrainType)

ResourceType = _reflection.GeneratedProtocolMessageType('ResourceType', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCETYPE,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.types.ResourceType)
  ))
_sym_db.RegisterMessage(ResourceType)

UnitType = _reflection.GeneratedProtocolMessageType('UnitType', (_message.Message,), dict(
  DESCRIPTOR = _UNITTYPE,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.types.UnitType)
  ))
_sym_db.RegisterMessage(UnitType)

ActionType = _reflection.GeneratedProtocolMessageType('ActionType', (_message.Message,), dict(

  ResourceCost = _reflection.GeneratedProtocolMessageType('ResourceCost', (_message.Message,), dict(
    DESCRIPTOR = _ACTIONTYPE_RESOURCECOST,
    __module__ = 'types_pb2'
    # @@protoc_insertion_point(class_scope:reset.proto.types.ActionType.ResourceCost)
    ))
  ,
  DESCRIPTOR = _ACTIONTYPE,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:reset.proto.types.ActionType)
  ))
_sym_db.RegisterMessage(ActionType)
_sym_db.RegisterMessage(ActionType.ResourceCost)


# @@protoc_insertion_point(module_scope)
